correction

diff --git a/.github/workflows/deploy-docker.yaml b/.github/workflows/deploy-docker.yaml
--- a/.github/workflows/deploy-docker.yaml
+++ b/.github/workflows/deploy-docker.yaml
@@ -1,8 +1,9 @@
+
 name: Build Docker image & push
 
 on:
   push:
-    branches: [main]
+    branches: [main , dev-madhur]
   release:
     types: [published]
   pull_request:
@@ -19,6 +20,19 @@ jobs:
     steps:
       - name: Check out code into the Go module directory
         uses: actions/checkout@v4
+
+      - name: Validate config file naming
+        run: |
+          echo "🔍 Checking config file naming..."
+
+          if find . -type f -name "config-validator.toml" | grep -q .; then
+            echo "ERROR: Invalid config file name detected!"
+            echo "Rename 'config-validator.toml' to 'config.toml'"
+            find . -type f -name "config-validator.toml"
+            exit 1
+          fi
+
+          echo "Config naming is correct."        
 
       - name: Extract metadata (tags, labels) for Docker
         id: meta
